# Generated by Django 6.0 on 2025-12-14 05:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('students', '0004_alter_students_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Scores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='考试名称')),
                ('student_name', models.CharField(max_length=10, verbose_name='学生姓名')),
                ('student_number', models.CharField(max_length=10, verbose_name='学号')),
                ('chinese_score', models.CharField(max_length=10, verbose_name='语文')),
                ('math_score', models.CharField(max_length=10, verbose_name='数学')),
                ('english_score', models.CharField(max_length=10, verbose_name='英语')),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='scores', to='students.students', verbose_name='学生')),
            ],
            options={
                'verbose_name': '成绩',
                'verbose_name_plural': '成绩管理',
                'db_table': 'scores',
            },
        ),
    ]
