# Generated by Django 6.0 on 2025-12-14 06:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scores', '0001_initial'),
        ('students', '0004_alter_students_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scores',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scores', to='students.students', verbose_name='学生'),
        ),
    ]
