# Generated by Django 6.0 on 2025-12-14 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scores', '0002_alter_scores_student'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scores',
            name='chinese_score',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True, verbose_name='语文'),
        ),
        migrations.AlterField(
            model_name='scores',
            name='english_score',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True, verbose_name='英语'),
        ),
        migrations.AlterField(
            model_name='scores',
            name='math_score',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True, verbose_name='数学'),
        ),
    ]
