# Generated by Django 6.0 on 2025-12-14 16:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grades', '0001_initial'),
        ('scores', '0003_alter_scores_chinese_score_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='scores',
            options={'ordering': ['-id'], 'verbose_name': '成绩', 'verbose_name_plural': '成绩管理'},
        ),
        migrations.AddField(
            model_name='scores',
            name='grade',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='scores', to='grades.grades', verbose_name='班级'),
            preserve_default=False,
        ),
    ]
