# Generated by Django 6.0 on 2025-12-11 08:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_alter_students_grade'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='students',
            options={'ordering': ['pk'], 'verbose_name': '学生', 'verbose_name_plural': '学生管理'},
        ),
    ]
