# Generated by Django 6.0 on 2025-12-07 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Grades',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade_name', models.CharField(max_length=50, unique=True, verbose_name='班级名称')),
                ('grade_code', models.CharField(max_length=50, unique=True, verbose_name='班级编号')),
            ],
            options={
                'verbose_name': '班级',
                'verbose_name_plural': '班级管理',
                'db_table': 'grades',
            },
        ),
    ]
