# Generated by Django 6.0 on 2025-12-11 09:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grades', '0001_initial'),
        ('teachers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teachers',
            name='grade',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='grades.grades', verbose_name='班级'),
        ),
    ]
