# Generated by Django 6.0 on 2025-12-11 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0002_alter_teachers_grade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teachers',
            name='phone',
            field=models.CharField(max_length=11, unique=True, verbose_name='电话'),
        ),
    ]
